In [1]:
import pandas as pd

In [ ]:
#series 1D
#dataframe 2D

In [ ]:
#series 
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
dic ={
    "name":["Aman","Shalu","Priti", "kajal", "neha"],
    "age":[20,24,25,26,22]
}
df =pd.DataFrame(dic)
df.head()

    name  age
0   Aman   20
1  Shalu   24
2  Priti   25
3  kajal   26
4   neha   22

In [7]:
#add column
marks = [86,54,76,78,73]
df.insert(1,"MMarks",marks)
df.head()

    name  MMarks  Marks  age
0   Aman      86     86   20
1  Shalu      54     54   24
2  Priti      76     76   25
3  kajal      78     78   26
4   neha      73     73   22

In [9]:
course =["BCA","BTECH","BTECH","BBA","MBA"]
df["Course"]= course
df.sample()

    name  MMarks  Marks  age Course
1  Shalu      54     54   24  BTECH

In [11]:
id = [12,23,34,45,56]
df["ID"] = id
df.sample()

   name  MMarks  Marks  age Course  ID
4  neha      73     73   22    MBA  56

In [22]:
di1 ={
    "ID":[12,23,34,45,56],
    "Subject":["M4","TAFL","OS",None,"AI"] 
               
}

df1 =pd.DataFrame(di1)
data = pd.merge(df,df1,on="ID", how="inner")

In [23]:
data.tail()

    name  MMarks  Marks  age Course  ID Subject
0   Aman      86     86   20    BCA  12      M4
1  Shalu      54     54   24  BTECH  23    TAFL
2  Priti      76     76   25  BTECH  34      OS
3  kajal      78     78   26    BBA  45     NaN
4   neha      73     73   22    MBA  56      AI

In [30]:
df = pd.read_csv("data/tipsdataset.csv")

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   gender      244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [32]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [34]:
data.isnull().sum()

name       0
MMarks     0
Marks      0
age        0
Course     0
ID         0
Subject    1
dtype: int64